version: '3.8'
services:
  postgres:
    image: apache/age:latest
    environment:
      POSTGRES_DB: covid_analysis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    command: postgres -c shared_preload_libraries=age,pg_stat_statements -c max_connections=200

volumes:
  postgres_data:
